import type { Metadata } from "next";

import "./globals.css";

import ThemeProvider from "@/providers/theme-provider";

import { Inter } from "next/font/google";

import Banner from "@/components/banner";
import { Sidebar } from "@/components/sidebar";
import TopNavigation from "@/components/top-navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <Banner />
          <TopNavigation />
          <div className="flex w-full">
            <Sidebar className="w-52" />
            <div className="w-full">{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
