import type { Metadata } from "next";

import "./globals.css";

import ThemeProvider from "@/providers/theme-provider";

import { Inter } from "next/font/google";

import { Sidebar } from "@/components/sidebar";
import ThemeSwitcher from "@/components/theme-switcher";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <div className="border-b">
            <div className="flex h-16 items-center px-4">
              <h1 className="pl-3 text-4xl font-bold">Photos App</h1>
              <div className="ml-auto flex items-center space-x-4">
                <ThemeSwitcher />
                <Avatar>
                  <AvatarImage src="https://github.com/shadcn.png" alt="@shadcn" />
                  <AvatarFallback>CN</AvatarFallback>
                </Avatar>
              </div>
            </div>
          </div>
          <div className="flex w-full">
            <Sidebar className="w-52" />
            <div className="w-full">{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
